{{- range .Values.groups }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .groupName }}-rolebinding
  namespace: {{ .namespace }}
subjects:
  - kind: Group
    name: {{ .groupName }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole                       # Referring to a ClusterRole, e.g., cluster-admin, view, edit
  name: {{ .roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
