apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xvpcs.myvpc.example.com  # Changed to match the group and plural
spec:
  group: myvpc.example.com  # Changed group to avoid protected namespaces
  names:
    kind: XVPC
    plural: xvpcs  # Lowercase plural
  claimNames:
    kind: cvpc
    plural: cvpcs
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
              cidrBlock:
                type: string
            required:
              - region
              - cidrBlock
